### ISSUE TITLE
cfg(debug_assertions) unnecessary

### ISSUE THREAD

**Issue by xrl** [xaviershay/rust-puzzlefighter#15]
I cloned the repo and was unable to run the project using `cargo run --release` because `Piece::new` was no longer being compiled.

```
impl Piece {
    #[cfg(debug_assertions)]
    pub fn new(b1: Block, b2: Block) -> Self {
        Piece {
            blocks: [b1, b2],
            position: GridPosition::new(0, 0),
            direction: Direction::Up,
            floor_kicks: 0,
        }
    }
```

Until now I was unaware of `debug_assertions` config flag until now but I don't think you want to hide the `Piece::new` ever. In any case, removing the `#[cfg(debug_assertions)]` got me unblocked and I was able to run the game in a release build. Neat game!

**Comment by xaviershay** [comment]
Thanks for trying! I need to get an AI going so you can play 1P :)

This was in here from way back wrestling with dead code warnings and I didn't quite understand what was happening. Thanks for reporting.

**Comment by xrl** [comment]
:+1:
