### ISSUE TITLE
FBO crash on Linux

### ISSUE THREAD

**Issue by MagaTailor** [xaviershay/rust-puzzlefighter#18]
```
Running `target/release/puzzlefighter`
thread '<main>' panicked at 'Tried to do something with an FBO without FBO support!', /home/petevine/.cargo/registry/src/github.com-48ad6e4054423464/gfx_device_gl-0.5.0/src/lib.rs:343
```

**Comment by xaviershay** [comment]
I don't know what FBO is and I don't have a linux machine to test. So sorry I can't help with this one :/ Looks like an opengl thing maybe?

**Comment by MagaTailor** [comment]
Naturally; didn't you know you were using OpenGL via a crate called `gfx_device_gl-0.5.0`?

Never mind!

**Comment by xaviershay** [comment]
haha all that stuff is a) months old, my brain has forgotten, and b) likely cargo culted :)

**Comment by MagaTailor** [comment]
:)

In that case you could safely splash a big notice in the README:

**OpenGL 3 required**  

cause that's what these rust libs default to. It could probably be made to work with OGL 2.0 with little hacking.

**Comment by xaviershay** [comment]
Done in https://github.com/xaviershay/rust-puzzlefighter/commit/c02965a9deff5b4b22c4f2e6c78d9d83d51b3388

Thanks!
