### ISSUE TITLE
What is it about?

### ISSUE THREAD

**Issue by PhiLhoSoft** [xaviershay/rust-puzzlefighter#19]
I understand this is a game made with Rust, as I am coming from https://github.com/PistonDevelopers/piston/wiki/Games-Made-With-Piston

But you didn't provide a description of your repository: "_No description or website provided._".

And if the screenshot looks nice, I see no description of the game itself. How is it played? What are these different tiles? You should at least provide a link to a page describing the original game...

**Comment by xaviershay** [comment]
Thanks for the report! Still room for improvement, but I pushed a basic description to the README.
